-- HealthHub schema for MySQL 8+
-- Generated from com.healthhub.service.Persistencia

CREATE DATABASE IF NOT EXISTS healthhub
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE healthhub;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS NOTIFICACION;
DROP TABLE IF EXISTS ENTRADA_HISTORIAL;
DROP TABLE IF EXISTS HISTORIAL_CLINICO;
DROP TABLE IF EXISTS TURNO;
DROP TABLE IF EXISTS DISPONIBILIDAD;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS MEDICO;
DROP TABLE IF EXISTS PACIENTE;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE PACIENTE (
  DNI VARCHAR(20) PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDO VARCHAR(100) NOT NULL,
  TELEFONO VARCHAR(30) NOT NULL,
  OBRA_SOCIAL VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE MEDICO (
  MATRICULA VARCHAR(20) PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDO VARCHAR(100) NOT NULL,
  ESPECIALIDAD VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EMPLEADO (
  LEGAJO VARCHAR(20) PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  ROL VARCHAR(30) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE DISPONIBILIDAD (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  MATRICULA VARCHAR(20) NOT NULL,
  DIA INT NOT NULL,
  HORA_INICIO TIME NOT NULL,
  HORA_FIN TIME NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_DISPONIBILIDAD_MEDICO
    FOREIGN KEY (MATRICULA) REFERENCES MEDICO(MATRICULA)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE TURNO (
  ID VARCHAR(40) PRIMARY KEY,
  DNI_PACIENTE VARCHAR(20) NOT NULL,
  MATRICULA_MEDICO VARCHAR(20) NOT NULL,
  FECHA_HORA TIMESTAMP NOT NULL,
  ESTADO VARCHAR(30) NOT NULL,
  SOBRETURNO BOOLEAN NOT NULL,
  CONSTRAINT FK_TURNO_PACIENTE
    FOREIGN KEY (DNI_PACIENTE) REFERENCES PACIENTE(DNI)
    ON DELETE CASCADE,
  CONSTRAINT FK_TURNO_MEDICO
    FOREIGN KEY (MATRICULA_MEDICO) REFERENCES MEDICO(MATRICULA)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE HISTORIAL_CLINICO (
  DNI_PACIENTE VARCHAR(20) PRIMARY KEY,
  CONSTRAINT FK_HISTORIAL_PACIENTE
    FOREIGN KEY (DNI_PACIENTE) REFERENCES PACIENTE(DNI)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ENTRADA_HISTORIAL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DNI_PACIENTE VARCHAR(20) NOT NULL,
  FECHA TIMESTAMP NOT NULL,
  RESUMEN VARCHAR(4000) NOT NULL,
  DIAGNOSTICO VARCHAR(4000) NOT NULL,
  ESTUDIOS VARCHAR(4000) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ENTRADA_HISTORIAL
    FOREIGN KEY (DNI_PACIENTE) REFERENCES HISTORIAL_CLINICO(DNI_PACIENTE)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE NOTIFICACION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LEGAJO VARCHAR(20) NOT NULL,
  MENSAJE VARCHAR(1000) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_NOTIFICACION_EMPLEADO
    FOREIGN KEY (LEGAJO) REFERENCES EMPLEADO(LEGAJO)
    ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT INTO EMPLEADO (LEGAJO, NOMBRE, ROL) VALUES
  ('1000', 'Lucia Romero', 'ADMINISTRADOR'),
  ('2000', 'Valeria Gomez', 'RECEPCIONISTA'),
  ('3000', 'Martin Paredes', 'MEDICO');

INSERT INTO MEDICO (MATRICULA, NOMBRE, APELLIDO, ESPECIALIDAD) VALUES
  ('MP-101', 'Martin', 'Paredes', 'Clinica general'),
  ('MP-202', 'Sofia', 'Suarez', 'Pediatria');

INSERT INTO PACIENTE (DNI, NOMBRE, APELLIDO, TELEFONO, OBRA_SOCIAL) VALUES
  ('40111222', 'Ana', 'Lopez', '1160001000', 'OSDE'),
  ('40999888', 'Bruno', 'Diaz', '1160002000', 'Swiss Medical');

INSERT INTO DISPONIBILIDAD (MATRICULA, DIA, HORA_INICIO, HORA_FIN) VALUES
  ('MP-101', 1, '08:00:00', '14:00:00'),
  ('MP-101', 3, '09:00:00', '15:00:00'),
  ('MP-202', 2, '10:00:00', '16:00:00'),
  ('MP-202', 4, '09:00:00', '13:00:00');

INSERT INTO HISTORIAL_CLINICO (DNI_PACIENTE) VALUES
  ('40111222'),
  ('40999888');

INSERT INTO ENTRADA_HISTORIAL (DNI_PACIENTE, FECHA, RESUMEN, DIAGNOSTICO, ESTUDIOS) VALUES
  ('40111222', '2026-06-01 09:00:00', 'Consulta inicial', 'Paciente estable', 'Sin estudios pendientes'),
  ('40111222', '2026-06-03 10:30:00', 'Control general', 'Evolucion favorable', 'Analisis de rutina'),
  ('40999888', '2026-06-02 11:00:00', 'Control pediatrico', 'Sin hallazgos relevantes', 'Vacunacion al dia'),
  ('40999888', '2026-06-04 12:15:00', 'Seguimiento', 'Buen estado general', 'Sin estudios requeridos');

INSERT INTO TURNO (ID, DNI_PACIENTE, MATRICULA_MEDICO, FECHA_HORA, ESTADO, SOBRETURNO) VALUES
  ('T-001', '40111222', 'MP-101', '2026-06-08 09:00:00', 'PROGRAMADO', FALSE),
  ('T-002', '40999888', 'MP-202', '2026-06-10 10:00:00', 'PROGRAMADO', FALSE);

INSERT INTO NOTIFICACION (LEGAJO, MENSAJE) VALUES
  ('3000', 'Bienvenida: ya podés gestionar la agenda desde el panel.'),
  ('3000', 'Tenés 2 turnos programados esta semana.'),
  ('2000', 'Bienvenida: revisá la agenda y los pacientes cargados.'),
  ('1000', 'Acceso de administrador habilitado para HealthHub.');
