erDiagram
    %% Base de datos H2 embebida
    EMPLEADO {
        string legajo PK
        string nombre
        string rol
    }

    PACIENTE {
        string dni PK
        string nombre
        string apellido
        string telefono
        string obraSocial
    }

    MEDICO {
        string matricula PK
        string nombre
        string apellido
        string especialidad
    }

    DISPONIBILIDAD {
        string matricula FK
        string dia
        string horaInicio
        string horaFin
    }

    TURNO {
        string id PK
        string dniPaciente FK
        string matriculaMedico FK
        datetime fechaHora
        string estado
        boolean sobreturno
    }

    HISTORIAL_CLINICO {
        string dniPaciente PK, FK
    }

    ENTRADA_HISTORIAL {
        string id PK
        string dniPaciente FK
        datetime fecha
        string resumen
        string diagnostico
        string estudios
    }

    NOTIFICACION {
        string legajo FK
        string mensaje
    }

    PACIENTE ||--|| HISTORIAL_CLINICO : posee
    HISTORIAL_CLINICO ||--o{ ENTRADA_HISTORIAL : contiene
    MEDICO ||--o{ DISPONIBILIDAD : define
    PACIENTE ||--o{ TURNO : solicita
    MEDICO ||--o{ TURNO : atiende
    EMPLEADO ||--o{ NOTIFICACION : recibe
